(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const safe=(v,f)=>{try{return JSON.parse(v)}catch{return f}},storage=(()=>{try{const x=window.localStorage,k='__vm_dash_probe';x.setItem(k,'1');x.removeItem(k);return x}catch{const m=new Map();return{getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}}})(),money=n=>Number(n||0).toFixed(3),esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const seed=[['orma','ORMA','ORMA','Footwear','#c59d5f','#efe1c5','#28221d','سالم'],['noor','نور للعطور','NOOR PERFUMERY','Perfume','#ad7b5a','#ead6c7','#251c18','ليان'],['tech','تيك هب','TECH HUB','Electronics','#4f7d86','#bcd6da','#172126','ريان'],['safa','صفا','SAFA','Fashion','#8f745f','#e5d8ce','#241f1b','مها'],['dar','دار','DAR HOME','Home','#7c8a70','#d7dfcf','#1d221b','نور'],['cafe','كافيه سكوير','CAFE SQUARE','Food','#855d43','#e6cdb9','#211812','عمر'],['hadiya','هدية','HADIYA','Gifts','#9b6f82','#ead8df','#261d21','هند'],['move','موف','MOVE','Sports','#65756f','#d4ddd9','#1c2320','مازن'],['little','ليتل لاب','LITTLE LAB','Kids','#8d7c66','#e7ddce','#211d18','سارة'],['lux','أتريوم لوكس','ATRIUM LUX','Luxury','#7e6b43','#e3d6b9','#191712','آدم']];
const zs=[-18,-9,0,9,18],runtime=safe(storage.getItem('vm-store-state')||'{}',{}),cfg=safe(storage.getItem('vm-store-config')||'{}',{});
const stores=seed.map((s,i)=>Object.assign({id:`store-${s[0]}`,merchantId:`merchant-${s[0]}`,nameAr:s[1],nameEn:s[2],category:s[3],primary:s[4],accent:s[5],wall:s[6],employee:s[7],unit:i<5?`L0${i+1}`:`R0${i-4}`,x:i<5?-17:17,z:zs[i%5],side:i<5?'left':'right',rent:i%5===2?180:120,premium:i%5===2,status:runtime[`store-${s[0]}`]||'OPEN'},cfg[`store-${s[0]}`]||{}));
const pt=[['منتج سيجنتشر','Signature Piece',18,'◆'],['اختيار يومي','Daily Pick',9.5,'●'],['إصدار جديد','New Arrival',14.75,'✦'],['اختيار فاخر','Premium Pick',27,'⬟']],inv=safe(storage.getItem('vm-product-inventory')||'{}',{});
const products=stores.flatMap((st,si)=>pt.map((p,i)=>({id:`${st.id}-p${i+1}`,storeId:st.id,sku:`${st.id.replace('store-','').toUpperCase()}-${100+i}`,nameAr:`${p[0]} ${i+1}`,nameEn:`${p[1]} ${i+1}`,price:Number((p[2]+si*.65).toFixed(3)),inventory:inv[`${st.id}-p${i+1}`]??(6+((si*3+i*5)%24)),icon:p[3]})));
const orders=safe(storage.getItem('vm-standalone-orders')||'[]',[]),ops=safe(storage.getItem('vm-owner-ops')||'{"events":1,"ads":2}',{events:1,ads:2});let bc=null;try{bc=new BroadcastChannel('virtual-mall-world-v1')}catch{}
function send(m){try{bc?.postMessage({...m,id:'dashboard',mid:crypto.randomUUID?.()||String(Date.now()),at:Date.now()})}catch{}}
function saveStores(){storage.setItem('vm-store-state',JSON.stringify(Object.fromEntries(stores.map(s=>[s.id,s.status]))));storage.setItem('vm-store-config',JSON.stringify(Object.fromEntries(stores.map(s=>[s.id,{nameAr:s.nameAr,nameEn:s.nameEn,primary:s.primary,employee:s.employee,taglineAr:s.taglineAr||'',taglineEn:s.taglineEn||''}]))));send({type:'store-state',stores:stores.map(s=>({id:s.id,status:s.status,rent:s.rent,premium:s.premium}))});send({type:'store-config',config:Object.fromEntries(stores.map(s=>[s.id,{nameAr:s.nameAr,nameEn:s.nameEn,primary:s.primary,employee:s.employee}]))})}
function saveInv(){storage.setItem('vm-product-inventory',JSON.stringify(Object.fromEntries(products.map(p=>[p.id,p.inventory]))));send({type:'product-inventory',inventory:Object.fromEntries(products.map(p=>[p.id,p.inventory]))})}
function saveOrders(){storage.setItem('vm-standalone-orders',JSON.stringify(orders));send({type:'orders-refresh'})}
function toast(v){const e=$('#toast');if(!e)return;e.textContent=v;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1700)}
window.VM={$, $$, safe,storage,money,esc,stores,products,orders,ops,saveStores,saveInv,saveOrders,send,toast};})();